/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    organisations: Organisation;
    'api-keys': ApiKey;
    'module-entitlements': ModuleEntitlement;
    'wordpress-connections': WordpressConnection;
    'google-connections': GoogleConnection;
    'google-oauth-states': GoogleOauthState;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    organisations: OrganisationsSelect<false> | OrganisationsSelect<true>;
    'api-keys': ApiKeysSelect<false> | ApiKeysSelect<true>;
    'module-entitlements': ModuleEntitlementsSelect<false> | ModuleEntitlementsSelect<true>;
    'wordpress-connections': WordpressConnectionsSelect<false> | WordpressConnectionsSelect<true>;
    'google-connections': GoogleConnectionsSelect<false> | GoogleConnectionsSelect<true>;
    'google-oauth-states': GoogleOauthStatesSelect<false> | GoogleOauthStatesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'superadmin' | 'customer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * A team/account. Any module (WordPress, future integrations) attaches to one of these.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organisations".
 */
export interface Organisation {
  id: number;
  /**
   * Optional display name for this team.
   */
  name?: string | null;
  members?:
    | {
        user: number | User;
        role: 'admin' | 'member';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys".
 */
export interface ApiKey {
  id: number;
  user: number | User;
  name: string;
  hashedKey: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Which modules are enabled for which organisation. Superadmin-only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "module-entitlements".
 */
export interface ModuleEntitlement {
  id: number;
  organisation: number | Organisation;
  moduleSlug: 'wordpress' | 'google-search-console' | 'google-analytics';
  enabled?: boolean | null;
  source?: ('manual' | 'billing' | 'migration') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * WordPress sites connected to an organisation. An organisation may connect more than one.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wordpress-connections".
 */
export interface WordpressConnection {
  id: number;
  organisation: number | Organisation;
  /**
   * Optional nickname to tell this site apart from others, e.g. "Main blog".
   */
  label?: string | null;
  /**
   * e.g. https://example.com (no trailing slash)
   */
  siteUrl: string;
  username: string;
  /**
   * WordPress Application Password (24-char, encrypted at rest).
   */
  appPassword: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Google OAuth connections shared by the Google Site Hub modules. Server-only - see modules/google-connections/index.ts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-connections".
 */
export interface GoogleConnection {
  id: number;
  organisation: number | Organisation;
  /**
   * User-entered display label - reporting scopes never return an email to derive one from.
   */
  googleAccountLabel: string;
  /**
   * Encrypted at rest. Never readable outside modules/google-connections's own server code.
   */
  accessToken?: string | null;
  /**
   * Encrypted at rest. Never readable outside modules/google-connections's own server code.
   */
  refreshToken?: string | null;
  /**
   * The scopes Google's token response actually returned. Immutable after creation.
   */
  grantedScopes:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The capability this connection was authorized for. Immutable after creation.
   */
  scopeProfile: 'google-search-console' | 'google-analytics';
  tokenExpiresAt?: string | null;
  status: 'active' | 'needs_reconnect' | 'revoked';
  lastValidatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Short-lived OAuth state/PKCE records. Server-only - see modules/google-connections/index.ts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-oauth-states".
 */
export interface GoogleOauthState {
  id: number;
  state: string;
  codeVerifier: string;
  user: number | User;
  organisation: number | Organisation;
  capability: 'google-search-console' | 'google-analytics';
  /**
   * { "type": "connect" } or { "type": "reconnect", "connectionId": "..." }
   */
  flow:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'organisations';
        value: number | Organisation;
      } | null)
    | ({
        relationTo: 'api-keys';
        value: number | ApiKey;
      } | null)
    | ({
        relationTo: 'module-entitlements';
        value: number | ModuleEntitlement;
      } | null)
    | ({
        relationTo: 'wordpress-connections';
        value: number | WordpressConnection;
      } | null)
    | ({
        relationTo: 'google-connections';
        value: number | GoogleConnection;
      } | null)
    | ({
        relationTo: 'google-oauth-states';
        value: number | GoogleOauthState;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organisations_select".
 */
export interface OrganisationsSelect<T extends boolean = true> {
  name?: T;
  members?:
    | T
    | {
        user?: T;
        role?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys_select".
 */
export interface ApiKeysSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  hashedKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "module-entitlements_select".
 */
export interface ModuleEntitlementsSelect<T extends boolean = true> {
  organisation?: T;
  moduleSlug?: T;
  enabled?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wordpress-connections_select".
 */
export interface WordpressConnectionsSelect<T extends boolean = true> {
  organisation?: T;
  label?: T;
  siteUrl?: T;
  username?: T;
  appPassword?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-connections_select".
 */
export interface GoogleConnectionsSelect<T extends boolean = true> {
  organisation?: T;
  googleAccountLabel?: T;
  accessToken?: T;
  refreshToken?: T;
  grantedScopes?: T;
  scopeProfile?: T;
  tokenExpiresAt?: T;
  status?: T;
  lastValidatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-oauth-states_select".
 */
export interface GoogleOauthStatesSelect<T extends boolean = true> {
  state?: T;
  codeVerifier?: T;
  user?: T;
  organisation?: T;
  capability?: T;
  flow?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}