/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    organisations: Organisation;
    'api-keys': ApiKey;
    'module-entitlements': ModuleEntitlement;
    'wordpress-connections': WordpressConnection;
    'google-connections': GoogleConnection;
    'google-oauth-states': GoogleOauthState;
    'google-search-console-mappings': GoogleSearchConsoleMapping;
    'google-analytics-mappings': GoogleAnalyticsMapping;
    'google-search-console-report-snapshots': GoogleSearchConsoleReportSnapshot;
    'google-search-console-report-refresh-leases': GoogleSearchConsoleReportRefreshLease;
    'google-search-console-quota-usage': GoogleSearchConsoleQuotaUsage;
    'google-analytics-report-snapshots': GoogleAnalyticsReportSnapshot;
    'google-analytics-report-refresh-leases': GoogleAnalyticsReportRefreshLease;
    'google-analytics-quota-usage': GoogleAnalyticsQuotaUsage;
    'ga4-property-quota': Ga4PropertyQuota;
    'ga4-project-property-quota': Ga4ProjectPropertyQuota;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    organisations: OrganisationsSelect<false> | OrganisationsSelect<true>;
    'api-keys': ApiKeysSelect<false> | ApiKeysSelect<true>;
    'module-entitlements': ModuleEntitlementsSelect<false> | ModuleEntitlementsSelect<true>;
    'wordpress-connections': WordpressConnectionsSelect<false> | WordpressConnectionsSelect<true>;
    'google-connections': GoogleConnectionsSelect<false> | GoogleConnectionsSelect<true>;
    'google-oauth-states': GoogleOauthStatesSelect<false> | GoogleOauthStatesSelect<true>;
    'google-search-console-mappings': GoogleSearchConsoleMappingsSelect<false> | GoogleSearchConsoleMappingsSelect<true>;
    'google-analytics-mappings': GoogleAnalyticsMappingsSelect<false> | GoogleAnalyticsMappingsSelect<true>;
    'google-search-console-report-snapshots': GoogleSearchConsoleReportSnapshotsSelect<false> | GoogleSearchConsoleReportSnapshotsSelect<true>;
    'google-search-console-report-refresh-leases': GoogleSearchConsoleReportRefreshLeasesSelect<false> | GoogleSearchConsoleReportRefreshLeasesSelect<true>;
    'google-search-console-quota-usage': GoogleSearchConsoleQuotaUsageSelect<false> | GoogleSearchConsoleQuotaUsageSelect<true>;
    'google-analytics-report-snapshots': GoogleAnalyticsReportSnapshotsSelect<false> | GoogleAnalyticsReportSnapshotsSelect<true>;
    'google-analytics-report-refresh-leases': GoogleAnalyticsReportRefreshLeasesSelect<false> | GoogleAnalyticsReportRefreshLeasesSelect<true>;
    'google-analytics-quota-usage': GoogleAnalyticsQuotaUsageSelect<false> | GoogleAnalyticsQuotaUsageSelect<true>;
    'ga4-property-quota': Ga4PropertyQuotaSelect<false> | Ga4PropertyQuotaSelect<true>;
    'ga4-project-property-quota': Ga4ProjectPropertyQuotaSelect<false> | Ga4ProjectPropertyQuotaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'superadmin' | 'customer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * A team/account. Any module (WordPress, future integrations) attaches to one of these.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organisations".
 */
export interface Organisation {
  id: number;
  /**
   * Optional display name for this team.
   */
  name?: string | null;
  members?:
    | {
        user: number | User;
        role: 'admin' | 'member';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys".
 */
export interface ApiKey {
  id: number;
  user: number | User;
  name: string;
  hashedKey: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Which modules are enabled for which organisation. Superadmin-only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "module-entitlements".
 */
export interface ModuleEntitlement {
  id: number;
  organisation: number | Organisation;
  moduleSlug: 'wordpress' | 'google-search-console' | 'google-analytics';
  enabled?: boolean | null;
  source?: ('manual' | 'billing' | 'migration') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * WordPress sites connected to an organisation. An organisation may connect more than one.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wordpress-connections".
 */
export interface WordpressConnection {
  id: number;
  organisation: number | Organisation;
  /**
   * Optional nickname to tell this site apart from others, e.g. "Main blog".
   */
  label?: string | null;
  /**
   * e.g. https://example.com (no trailing slash)
   */
  siteUrl: string;
  username: string;
  /**
   * WordPress Application Password (24-char, encrypted at rest).
   */
  appPassword: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Google OAuth connections shared by the Google Site Hub modules. Server-only - see modules/google-connections/index.ts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-connections".
 */
export interface GoogleConnection {
  id: number;
  organisation: number | Organisation;
  /**
   * User-entered display label - reporting scopes never return an email to derive one from.
   */
  googleAccountLabel: string;
  /**
   * Encrypted at rest. Never readable outside modules/google-connections's own server code.
   */
  accessToken?: string | null;
  /**
   * Encrypted at rest. Never readable outside modules/google-connections's own server code.
   */
  refreshToken?: string | null;
  /**
   * The scopes Google's token response actually returned. Immutable after creation.
   */
  grantedScopes:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The capability this connection was authorized for. Immutable after creation.
   */
  scopeProfile: 'google-search-console' | 'google-analytics';
  tokenExpiresAt?: string | null;
  status: 'active' | 'needs_reconnect' | 'revoked';
  lastValidatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Short-lived OAuth state/PKCE records. Server-only - see modules/google-connections/index.ts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-oauth-states".
 */
export interface GoogleOauthState {
  id: number;
  state: string;
  codeVerifier: string;
  user: number | User;
  organisation: number | Organisation;
  capability: 'google-search-console' | 'google-analytics';
  /**
   * { "type": "connect" } or { "type": "reconnect", "connectionId": "..." }
   */
  flow:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Which Search Console property reports for which connected WordPress site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-search-console-mappings".
 */
export interface GoogleSearchConsoleMapping {
  id: number;
  organisation: number | Organisation;
  wordpressConnection: number | WordpressConnection;
  googleConnection: number | GoogleConnection;
  /**
   * e.g. "sc-domain:example.com" or a URL-prefix property.
   */
  searchConsolePropertyUrl: string;
  /**
   * Who confirmed this mapping. May become unset if that user is later deleted.
   */
  confirmedBy?: (number | null) | User;
  confirmedAt: string;
  lastValidatedAt?: string | null;
  status: 'active' | 'needs_reconnect' | 'needs_remapping' | 'superseded';
  replacedAt?: string | null;
  replacedBy?: (number | null) | GoogleSearchConsoleMapping;
  updatedAt: string;
  createdAt: string;
}
/**
 * Which GA4 property reports for which connected WordPress site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-analytics-mappings".
 */
export interface GoogleAnalyticsMapping {
  id: number;
  organisation: number | Organisation;
  wordpressConnection: number | WordpressConnection;
  googleConnection: number | GoogleConnection;
  /**
   * GA4 property identifier.
   */
  ga4PropertyId: string;
  /**
   * The GA4 property's own configured reporting timezone, read from the Admin API at mapping time.
   */
  reportingTimezone?: string | null;
  /**
   * Who confirmed this mapping. May become unset if that user is later deleted.
   */
  confirmedBy?: (number | null) | User;
  confirmedAt: string;
  lastValidatedAt?: string | null;
  status: 'active' | 'needs_reconnect' | 'needs_remapping' | 'superseded';
  replacedAt?: string | null;
  replacedBy?: (number | null) | GoogleAnalyticsMapping;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cached Search Console report results. Server-only - see modules/google-search-console/reporting.ts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-search-console-report-snapshots".
 */
export interface GoogleSearchConsoleReportSnapshot {
  id: number;
  mapping: number | GoogleSearchConsoleMapping;
  reportType: 'post_performance' | 'compare_periods' | 'search_queries' | 'index_status';
  canonicalPostUrl: string;
  normalizedQueryParams?: string | null;
  dateRangeStart: string;
  dateRangeEnd: string;
  /**
   * Always America/Los_Angeles for Search Console.
   */
  timezone: string;
  fetchedAt: string;
  expiresAt: string;
  freshnessState: 'fresh' | 'stale' | 'delayed' | 'unavailable';
  /**
   * Normalised metrics/evidence only - never tokens or raw Google bodies.
   */
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Refresh-dedup leases for Search Console reports. Server-only - see modules/google-search-console/reporting.ts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-search-console-report-refresh-leases".
 */
export interface GoogleSearchConsoleReportRefreshLease {
  id: number;
  mapping: number | GoogleSearchConsoleMapping;
  reportType: 'post_performance' | 'compare_periods' | 'search_queries' | 'index_status';
  canonicalPostUrl: string;
  normalizedQueryParams?: string | null;
  dateRangeStart: string;
  dateRangeEnd: string;
  leaseHolder: string;
  leaseExpiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Per-organisation rate-limit counters for Search Console requests. Server-only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-search-console-quota-usage".
 */
export interface GoogleSearchConsoleQuotaUsage {
  id: number;
  organisation: number | Organisation;
  wordpressConnection: number | WordpressConnection;
  windowStart: string;
  requestCount: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cached GA4 report results. Server-only - see modules/google-analytics/reporting.ts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-analytics-report-snapshots".
 */
export interface GoogleAnalyticsReportSnapshot {
  id: number;
  mapping: number | GoogleAnalyticsMapping;
  reportType: 'post_performance' | 'compare_periods';
  canonicalPostUrl: string;
  normalizedQueryParams?: string | null;
  dateRangeStart: string;
  dateRangeEnd: string;
  /**
   * The mapped GA4 property's own configured reporting timezone.
   */
  timezone: string;
  fetchedAt: string;
  expiresAt: string;
  freshnessState: 'fresh' | 'stale' | 'delayed' | 'unavailable';
  /**
   * Normalised metrics/evidence only - never tokens or raw Google bodies.
   */
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Refresh-dedup leases for GA4 reports. Server-only - see modules/google-analytics/reporting.ts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-analytics-report-refresh-leases".
 */
export interface GoogleAnalyticsReportRefreshLease {
  id: number;
  mapping: number | GoogleAnalyticsMapping;
  reportType: 'post_performance' | 'compare_periods';
  canonicalPostUrl: string;
  normalizedQueryParams?: string | null;
  dateRangeStart: string;
  dateRangeEnd: string;
  leaseHolder: string;
  leaseExpiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Per-organisation rate-limit counters for GA4 requests. Server-only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-analytics-quota-usage".
 */
export interface GoogleAnalyticsQuotaUsage {
  id: number;
  organisation: number | Organisation;
  wordpressConnection: number | WordpressConnection;
  windowStart: string;
  requestCount: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * GA4 Data API property-wide quota, as last observed from returnPropertyQuota. Server-only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ga4-property-quota".
 */
export interface Ga4PropertyQuota {
  id: number;
  ga4PropertyId: string;
  tokensRemaining?: number | null;
  tokensPerHour?: number | null;
  tokensPerDay?: number | null;
  concurrentRequests?: number | null;
  lastObservedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * GA4 Data API per-(property, Google Cloud project) quota. Server-only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ga4-project-property-quota".
 */
export interface Ga4ProjectPropertyQuota {
  id: number;
  ga4PropertyId: string;
  googleCloudProjectId: string;
  tokensRemaining?: number | null;
  tokensPerHour?: number | null;
  tokensPerDay?: number | null;
  concurrentRequests?: number | null;
  lastObservedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'organisations';
        value: number | Organisation;
      } | null)
    | ({
        relationTo: 'api-keys';
        value: number | ApiKey;
      } | null)
    | ({
        relationTo: 'module-entitlements';
        value: number | ModuleEntitlement;
      } | null)
    | ({
        relationTo: 'wordpress-connections';
        value: number | WordpressConnection;
      } | null)
    | ({
        relationTo: 'google-connections';
        value: number | GoogleConnection;
      } | null)
    | ({
        relationTo: 'google-oauth-states';
        value: number | GoogleOauthState;
      } | null)
    | ({
        relationTo: 'google-search-console-mappings';
        value: number | GoogleSearchConsoleMapping;
      } | null)
    | ({
        relationTo: 'google-analytics-mappings';
        value: number | GoogleAnalyticsMapping;
      } | null)
    | ({
        relationTo: 'google-search-console-report-snapshots';
        value: number | GoogleSearchConsoleReportSnapshot;
      } | null)
    | ({
        relationTo: 'google-search-console-report-refresh-leases';
        value: number | GoogleSearchConsoleReportRefreshLease;
      } | null)
    | ({
        relationTo: 'google-search-console-quota-usage';
        value: number | GoogleSearchConsoleQuotaUsage;
      } | null)
    | ({
        relationTo: 'google-analytics-report-snapshots';
        value: number | GoogleAnalyticsReportSnapshot;
      } | null)
    | ({
        relationTo: 'google-analytics-report-refresh-leases';
        value: number | GoogleAnalyticsReportRefreshLease;
      } | null)
    | ({
        relationTo: 'google-analytics-quota-usage';
        value: number | GoogleAnalyticsQuotaUsage;
      } | null)
    | ({
        relationTo: 'ga4-property-quota';
        value: number | Ga4PropertyQuota;
      } | null)
    | ({
        relationTo: 'ga4-project-property-quota';
        value: number | Ga4ProjectPropertyQuota;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organisations_select".
 */
export interface OrganisationsSelect<T extends boolean = true> {
  name?: T;
  members?:
    | T
    | {
        user?: T;
        role?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys_select".
 */
export interface ApiKeysSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  hashedKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "module-entitlements_select".
 */
export interface ModuleEntitlementsSelect<T extends boolean = true> {
  organisation?: T;
  moduleSlug?: T;
  enabled?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wordpress-connections_select".
 */
export interface WordpressConnectionsSelect<T extends boolean = true> {
  organisation?: T;
  label?: T;
  siteUrl?: T;
  username?: T;
  appPassword?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-connections_select".
 */
export interface GoogleConnectionsSelect<T extends boolean = true> {
  organisation?: T;
  googleAccountLabel?: T;
  accessToken?: T;
  refreshToken?: T;
  grantedScopes?: T;
  scopeProfile?: T;
  tokenExpiresAt?: T;
  status?: T;
  lastValidatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-oauth-states_select".
 */
export interface GoogleOauthStatesSelect<T extends boolean = true> {
  state?: T;
  codeVerifier?: T;
  user?: T;
  organisation?: T;
  capability?: T;
  flow?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-search-console-mappings_select".
 */
export interface GoogleSearchConsoleMappingsSelect<T extends boolean = true> {
  organisation?: T;
  wordpressConnection?: T;
  googleConnection?: T;
  searchConsolePropertyUrl?: T;
  confirmedBy?: T;
  confirmedAt?: T;
  lastValidatedAt?: T;
  status?: T;
  replacedAt?: T;
  replacedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-analytics-mappings_select".
 */
export interface GoogleAnalyticsMappingsSelect<T extends boolean = true> {
  organisation?: T;
  wordpressConnection?: T;
  googleConnection?: T;
  ga4PropertyId?: T;
  reportingTimezone?: T;
  confirmedBy?: T;
  confirmedAt?: T;
  lastValidatedAt?: T;
  status?: T;
  replacedAt?: T;
  replacedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-search-console-report-snapshots_select".
 */
export interface GoogleSearchConsoleReportSnapshotsSelect<T extends boolean = true> {
  mapping?: T;
  reportType?: T;
  canonicalPostUrl?: T;
  normalizedQueryParams?: T;
  dateRangeStart?: T;
  dateRangeEnd?: T;
  timezone?: T;
  fetchedAt?: T;
  expiresAt?: T;
  freshnessState?: T;
  payload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-search-console-report-refresh-leases_select".
 */
export interface GoogleSearchConsoleReportRefreshLeasesSelect<T extends boolean = true> {
  mapping?: T;
  reportType?: T;
  canonicalPostUrl?: T;
  normalizedQueryParams?: T;
  dateRangeStart?: T;
  dateRangeEnd?: T;
  leaseHolder?: T;
  leaseExpiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-search-console-quota-usage_select".
 */
export interface GoogleSearchConsoleQuotaUsageSelect<T extends boolean = true> {
  organisation?: T;
  wordpressConnection?: T;
  windowStart?: T;
  requestCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-analytics-report-snapshots_select".
 */
export interface GoogleAnalyticsReportSnapshotsSelect<T extends boolean = true> {
  mapping?: T;
  reportType?: T;
  canonicalPostUrl?: T;
  normalizedQueryParams?: T;
  dateRangeStart?: T;
  dateRangeEnd?: T;
  timezone?: T;
  fetchedAt?: T;
  expiresAt?: T;
  freshnessState?: T;
  payload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-analytics-report-refresh-leases_select".
 */
export interface GoogleAnalyticsReportRefreshLeasesSelect<T extends boolean = true> {
  mapping?: T;
  reportType?: T;
  canonicalPostUrl?: T;
  normalizedQueryParams?: T;
  dateRangeStart?: T;
  dateRangeEnd?: T;
  leaseHolder?: T;
  leaseExpiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-analytics-quota-usage_select".
 */
export interface GoogleAnalyticsQuotaUsageSelect<T extends boolean = true> {
  organisation?: T;
  wordpressConnection?: T;
  windowStart?: T;
  requestCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ga4-property-quota_select".
 */
export interface Ga4PropertyQuotaSelect<T extends boolean = true> {
  ga4PropertyId?: T;
  tokensRemaining?: T;
  tokensPerHour?: T;
  tokensPerDay?: T;
  concurrentRequests?: T;
  lastObservedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ga4-project-property-quota_select".
 */
export interface Ga4ProjectPropertyQuotaSelect<T extends boolean = true> {
  ga4PropertyId?: T;
  googleCloudProjectId?: T;
  tokensRemaining?: T;
  tokensPerHour?: T;
  tokensPerDay?: T;
  concurrentRequests?: T;
  lastObservedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}